// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/workerapi/v1/worker.proto

// Versioning via package name, for future-proofing

package v1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/alta/protopatch/patch/gopb"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStatusEventsResponseStatus int32

const (
	StreamStatusEventsResponseUnspecified  StreamStatusEventsResponseStatus = 0
	StreamStatusEventsResponsePending      StreamStatusEventsResponseStatus = 1
	StreamStatusEventsResponseScheduling   StreamStatusEventsResponseStatus = 2
	StreamStatusEventsResponseInitializing StreamStatusEventsResponseStatus = 3
	StreamStatusEventsResponseRunning      StreamStatusEventsResponseStatus = 4
	StreamStatusEventsResponseSuccess      StreamStatusEventsResponseStatus = 5
	StreamStatusEventsResponseFailed       StreamStatusEventsResponseStatus = 6
	StreamStatusEventsResponseCancelled    StreamStatusEventsResponseStatus = 7
)

// Enum value maps for StreamStatusEventsResponse_Status.
var (
	StreamStatusEventsResponseStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PENDING",
		2: "SCHEDULING",
		3: "INITIALIZING",
		4: "RUNNING",
		5: "SUCCESS",
		6: "FAILED",
		7: "CANCELLED",
	}
	StreamStatusEventsResponseStatus_value = map[string]int32{
		"UNSPECIFIED":  0,
		"PENDING":      1,
		"SCHEDULING":   2,
		"INITIALIZING": 3,
		"RUNNING":      4,
		"SUCCESS":      5,
		"FAILED":       6,
		"CANCELLED":    7,
	}
)

func (x StreamStatusEventsResponseStatus) Enum() *StreamStatusEventsResponseStatus {
	p := new(StreamStatusEventsResponseStatus)
	*p = x
	return p
}

func (x StreamStatusEventsResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStatusEventsResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_workerapi_v1_worker_proto_enumTypes[0].Descriptor()
}

func (StreamStatusEventsResponseStatus) Type() protoreflect.EnumType {
	return &file_api_workerapi_v1_worker_proto_enumTypes[0]
}

func (x StreamStatusEventsResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStatusEventsResponse_Status.Descriptor instead.
func (StreamStatusEventsResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{4, 0}
}

// Empty messages, but exists for potential future usages
type StreamLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{0}
}

type StreamStatusEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamStatusEventsRequest) Reset() {
	*x = StreamStatusEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamStatusEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatusEventsRequest) ProtoMessage() {}

func (x *StreamStatusEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatusEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamStatusEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{1}
}

type StreamArtifactEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamArtifactEventsRequest) Reset() {
	*x = StreamArtifactEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamArtifactEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamArtifactEventsRequest) ProtoMessage() {}

func (x *StreamArtifactEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamArtifactEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamArtifactEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{2}
}

type StreamLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BuildID is the database ID of the build this log line belongs to.
	BuildID uint64 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// LogID is the worker's own ID of the log line. It's unique per build step
	// for a given build, but may have collisons across multiple steps or builds.
	// Not database value, but instead worker's own ID of the log line.
	LogID uint64 `protobuf:"varint,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// StepID is the worker's own ID of the step. It's unique for a given build,
	// but may have collisions across multiple builds.
	// Not database value, but instead worker's own ID of the step ID.
	StepID uint64 `protobuf:"varint,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Timestamp is when the log line was outputted from the build step.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Message is the log line text.
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *StreamLogsResponse) GetBuildID() uint64 {
	if x != nil {
		return x.BuildID
	}
	return 0
}

func (x *StreamLogsResponse) GetLogID() uint64 {
	if x != nil {
		return x.LogID
	}
	return 0
}

func (x *StreamLogsResponse) GetStepID() uint64 {
	if x != nil {
		return x.StepID
	}
	return 0
}

func (x *StreamLogsResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamStatusEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// EventID is the worker's own ID of the event the status.
	EventID uint64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// StepID is the worker's own ID of the step.
	StepID uint64 `protobuf:"varint,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Status is the step's status.
	Status StreamStatusEventsResponseStatus `protobuf:"varint,3,opt,name=status,proto3,enum=wharf.worker.v1.StreamStatusEventsResponse_Status" json:"status,omitempty"`
}

func (x *StreamStatusEventsResponse) Reset() {
	*x = StreamStatusEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamStatusEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatusEventsResponse) ProtoMessage() {}

func (x *StreamStatusEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatusEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamStatusEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StreamStatusEventsResponse) GetEventID() uint64 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *StreamStatusEventsResponse) GetStepID() uint64 {
	if x != nil {
		return x.StepID
	}
	return 0
}

func (x *StreamStatusEventsResponse) GetStatus() StreamStatusEventsResponseStatus {
	if x != nil {
		return x.Status
	}
	return StreamStatusEventsResponseUnspecified
}

type StreamArtifactEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ArtifactID is the worker's own ID of the artifact. It's unique per build
	// step for a given build, but may have collisons across multiple steps or
	// builds.
	ArtifactID uint64 `protobuf:"varint,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// StepID is the worker's own ID of the build step that produced the
	// artifact.
	StepID uint64 `protobuf:"varint,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Name is the name of the artifact.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StreamArtifactEventsResponse) Reset() {
	*x = StreamArtifactEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamArtifactEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamArtifactEventsResponse) ProtoMessage() {}

func (x *StreamArtifactEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamArtifactEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamArtifactEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *StreamArtifactEventsResponse) GetArtifactID() uint64 {
	if x != nil {
		return x.ArtifactID
	}
	return 0
}

func (x *StreamArtifactEventsResponse) GetStepID() uint64 {
	if x != nil {
		return x.StepID
	}
	return 0
}

func (x *StreamArtifactEventsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_workerapi_v1_worker_proto protoreflect.FileDescriptor

var file_api_workerapi_v1_worker_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0e, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x74, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74,
	0x65, 0x70, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9b, 0x02, 0x0a, 0x1a, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x77, 0x68,
	0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x49, 0x4e, 0x47, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x4c, 0x45, 0x44, 0x10, 0x07, 0x22, 0x6c, 0x0a, 0x1c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x32, 0xc9, 0x02, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12,
	0x57, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x22, 0x2e,
	0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x6f, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2a,
	0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x77, 0x68, 0x61,
	0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x75, 0x0a, 0x14, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x2c, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x42, 0x3c, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x76, 0x65, 0x72, 0x2d, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2f, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2d,
	0x63, 0x6d, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0xca, 0xb5, 0x03, 0x06, 0x08, 0x01, 0x52, 0x02, 0x49, 0x44, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_workerapi_v1_worker_proto_rawDescOnce sync.Once
	file_api_workerapi_v1_worker_proto_rawDescData = file_api_workerapi_v1_worker_proto_rawDesc
)

func file_api_workerapi_v1_worker_proto_rawDescGZIP() []byte {
	file_api_workerapi_v1_worker_proto_rawDescOnce.Do(func() {
		file_api_workerapi_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_workerapi_v1_worker_proto_rawDescData)
	})
	return file_api_workerapi_v1_worker_proto_rawDescData
}

var file_api_workerapi_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_workerapi_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_workerapi_v1_worker_proto_goTypes = []interface{}{
	(StreamStatusEventsResponseStatus)(0), // 0: wharf.worker.v1.StreamStatusEventsResponse.Status
	(*StreamLogsRequest)(nil),             // 1: wharf.worker.v1.StreamLogsRequest
	(*StreamStatusEventsRequest)(nil),     // 2: wharf.worker.v1.StreamStatusEventsRequest
	(*StreamArtifactEventsRequest)(nil),   // 3: wharf.worker.v1.StreamArtifactEventsRequest
	(*StreamLogsResponse)(nil),            // 4: wharf.worker.v1.StreamLogsResponse
	(*StreamStatusEventsResponse)(nil),    // 5: wharf.worker.v1.StreamStatusEventsResponse
	(*StreamArtifactEventsResponse)(nil),  // 6: wharf.worker.v1.StreamArtifactEventsResponse
	(*timestamp.Timestamp)(nil),           // 7: google.protobuf.Timestamp
}
var file_api_workerapi_v1_worker_proto_depIdxs = []int32{
	7, // 0: wharf.worker.v1.StreamLogsResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: wharf.worker.v1.StreamStatusEventsResponse.status:type_name -> wharf.worker.v1.StreamStatusEventsResponse.Status
	1, // 2: wharf.worker.v1.Worker.StreamLogs:input_type -> wharf.worker.v1.StreamLogsRequest
	2, // 3: wharf.worker.v1.Worker.StreamStatusEvents:input_type -> wharf.worker.v1.StreamStatusEventsRequest
	3, // 4: wharf.worker.v1.Worker.StreamArtifactEvents:input_type -> wharf.worker.v1.StreamArtifactEventsRequest
	4, // 5: wharf.worker.v1.Worker.StreamLogs:output_type -> wharf.worker.v1.StreamLogsResponse
	5, // 6: wharf.worker.v1.Worker.StreamStatusEvents:output_type -> wharf.worker.v1.StreamStatusEventsResponse
	6, // 7: wharf.worker.v1.Worker.StreamArtifactEvents:output_type -> wharf.worker.v1.StreamArtifactEventsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_workerapi_v1_worker_proto_init() }
func file_api_workerapi_v1_worker_proto_init() {
	if File_api_workerapi_v1_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_workerapi_v1_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamStatusEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamArtifactEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamStatusEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamArtifactEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_workerapi_v1_worker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_workerapi_v1_worker_proto_goTypes,
		DependencyIndexes: file_api_workerapi_v1_worker_proto_depIdxs,
		EnumInfos:         file_api_workerapi_v1_worker_proto_enumTypes,
		MessageInfos:      file_api_workerapi_v1_worker_proto_msgTypes,
	}.Build()
	File_api_workerapi_v1_worker_proto = out.File
	file_api_workerapi_v1_worker_proto_rawDesc = nil
	file_api_workerapi_v1_worker_proto_goTypes = nil
	file_api_workerapi_v1_worker_proto_depIdxs = nil
}
