// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/workerapi/v1/worker.proto

// Versioning via package name, for future-proofing

package v1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/alta/protopatch/patch/gopb"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusEventStatus int32

const (
	StatusEventUnknown      StatusEventStatus = 0
	StatusEventNone         StatusEventStatus = 1
	StatusEventScheduling   StatusEventStatus = 2
	StatusEventInitializing StatusEventStatus = 3
	StatusEventRunning      StatusEventStatus = 4
	StatusEventSuccess      StatusEventStatus = 5
	StatusEventFailed       StatusEventStatus = 6
	StatusEventCancelled    StatusEventStatus = 7
)

// Enum value maps for StatusEvent_Status.
var (
	StatusEventStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "NONE",
		2: "SCHEDULING",
		3: "INITIALIZING",
		4: "RUNNING",
		5: "SUCCESS",
		6: "FAILED",
		7: "CANCELLED",
	}
	StatusEventStatus_value = map[string]int32{
		"UNKNOWN":      0,
		"NONE":         1,
		"SCHEDULING":   2,
		"INITIALIZING": 3,
		"RUNNING":      4,
		"SUCCESS":      5,
		"FAILED":       6,
		"CANCELLED":    7,
	}
)

func (x StatusEventStatus) Enum() *StatusEventStatus {
	p := new(StatusEventStatus)
	*p = x
	return p
}

func (x StatusEventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusEventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_workerapi_v1_worker_proto_enumTypes[0].Descriptor()
}

func (StatusEventStatus) Type() protoreflect.EnumType {
	return &file_api_workerapi_v1_worker_proto_enumTypes[0]
}

func (x StatusEventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusEvent_Status.Descriptor instead.
func (StatusEventStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{4, 0}
}

type LogStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkSize int32 `protobuf:"varint,1,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *LogStreamRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

// Empty messages, but exists for potential future usages
type StatusEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusEventRequest) Reset() {
	*x = StatusEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEventRequest) ProtoMessage() {}

func (x *StatusEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEventRequest.ProtoReflect.Descriptor instead.
func (*StatusEventRequest) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{1}
}

type ArtifactEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArtifactEventRequest) Reset() {
	*x = ArtifactEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactEventRequest) ProtoMessage() {}

func (x *ArtifactEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactEventRequest.ProtoReflect.Descriptor instead.
func (*ArtifactEventRequest) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{2}
}

type LogStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Lines is an array of log lines to allow chunking log line streams.
	Lines []*LogLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
}

func (x *LogStream) Reset() {
	*x = LogStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStream) ProtoMessage() {}

func (x *LogStream) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStream.ProtoReflect.Descriptor instead.
func (*LogStream) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *LogStream) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type StatusEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// EventID is the worker's own ID of the event the status.
	EventID uint64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// StepID is the worker's own ID of the step.
	StepID uint64            `protobuf:"varint,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status StatusEventStatus `protobuf:"varint,3,opt,name=status,proto3,enum=wharf.worker.v1.StatusEvent_Status" json:"status,omitempty"`
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StatusEvent) GetEventID() uint64 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *StatusEvent) GetStepID() uint64 {
	if x != nil {
		return x.StepID
	}
	return 0
}

func (x *StatusEvent) GetStatus() StatusEventStatus {
	if x != nil {
		return x.Status
	}
	return StatusEventUnknown
}

type ArtifactEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ArtifactID is the worker's own ID of the artifact. It's unique per build
	// step for a given build, but may have collisons across multiple steps or
	// builds.
	ArtifactID uint32 `protobuf:"varint,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// StepID is the worker's own ID of the build step that produced the
	// artifact.
	StepID uint32 `protobuf:"varint,2,opt,name=stepID,proto3" json:"stepID,omitempty"`
	// Name is the name of the artifact.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ArtifactEvent) Reset() {
	*x = ArtifactEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactEvent) ProtoMessage() {}

func (x *ArtifactEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactEvent.ProtoReflect.Descriptor instead.
func (*ArtifactEvent) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactEvent) GetArtifactID() uint32 {
	if x != nil {
		return x.ArtifactID
	}
	return 0
}

func (x *ArtifactEvent) GetStepID() uint32 {
	if x != nil {
		return x.StepID
	}
	return 0
}

func (x *ArtifactEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// BuildID is the database ID of the build this log line belongs to.
	BuildID uint64 `protobuf:"varint,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// LogID is the worker's own ID of the log line. It's unique per build step
	// for a given build, but may have collisons across multiple steps or builds.
	// Not database value, but instead worker's own ID of the log line.
	LogID uint64 `protobuf:"varint,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// StepID is the worker's own ID of the step. It's unique for a given build,
	// but may have collisions across multiple builds.
	// Not database value, but instead worker's own ID of the step ID.
	StepID uint64 `protobuf:"varint,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Timestamp is when the log line was outputted from the build step.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Message is the log line text.
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_workerapi_v1_worker_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerapi_v1_worker_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_api_workerapi_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *LogLine) GetBuildID() uint64 {
	if x != nil {
		return x.BuildID
	}
	return 0
}

func (x *LogLine) GetLogID() uint64 {
	if x != nil {
		return x.LogID
	}
	return 0
}

func (x *LogLine) GetStepID() uint64 {
	if x != nil {
		return x.StepID
	}
	return 0
}

func (x *LogLine) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_workerapi_v1_worker_proto protoreflect.FileDescriptor

var file_api_workerapi_v1_worker_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0e, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3b, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2e,
	0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0xf6,
	0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70,
	0x49, 0x64, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x23, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x76, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x49, 0x4e, 0x47,
	0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43,
	0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x07, 0x22, 0x5c, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x65,
	0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x6f,
	0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x93, 0x02, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x0a, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x21, 0x2e, 0x77, 0x68, 0x61, 0x72,
	0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77,
	0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x30, 0x01, 0x12, 0x59, 0x0a, 0x12, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x23, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x5f, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x2e,
	0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x3c, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x76, 0x65, 0x72, 0x2d, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2f,
	0x77, 0x68, 0x61, 0x72, 0x66, 0x2d, 0x63, 0x6d, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0xca, 0xb5, 0x03, 0x06, 0x08, 0x01,
	0x52, 0x02, 0x49, 0x44, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_workerapi_v1_worker_proto_rawDescOnce sync.Once
	file_api_workerapi_v1_worker_proto_rawDescData = file_api_workerapi_v1_worker_proto_rawDesc
)

func file_api_workerapi_v1_worker_proto_rawDescGZIP() []byte {
	file_api_workerapi_v1_worker_proto_rawDescOnce.Do(func() {
		file_api_workerapi_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_workerapi_v1_worker_proto_rawDescData)
	})
	return file_api_workerapi_v1_worker_proto_rawDescData
}

var file_api_workerapi_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_workerapi_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_workerapi_v1_worker_proto_goTypes = []interface{}{
	(StatusEventStatus)(0),       // 0: wharf.worker.v1.StatusEvent.Status
	(*LogStreamRequest)(nil),     // 1: wharf.worker.v1.LogStreamRequest
	(*StatusEventRequest)(nil),   // 2: wharf.worker.v1.StatusEventRequest
	(*ArtifactEventRequest)(nil), // 3: wharf.worker.v1.ArtifactEventRequest
	(*LogStream)(nil),            // 4: wharf.worker.v1.LogStream
	(*StatusEvent)(nil),          // 5: wharf.worker.v1.StatusEvent
	(*ArtifactEvent)(nil),        // 6: wharf.worker.v1.ArtifactEvent
	(*LogLine)(nil),              // 7: wharf.worker.v1.LogLine
	(*timestamp.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_api_workerapi_v1_worker_proto_depIdxs = []int32{
	7, // 0: wharf.worker.v1.LogStream.lines:type_name -> wharf.worker.v1.LogLine
	0, // 1: wharf.worker.v1.StatusEvent.status:type_name -> wharf.worker.v1.StatusEvent.Status
	8, // 2: wharf.worker.v1.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: wharf.worker.v1.Worker.StreamLogs:input_type -> wharf.worker.v1.LogStreamRequest
	2, // 4: wharf.worker.v1.Worker.StreamStatusEvents:input_type -> wharf.worker.v1.StatusEventRequest
	3, // 5: wharf.worker.v1.Worker.StreamArtifactEvents:input_type -> wharf.worker.v1.ArtifactEventRequest
	4, // 6: wharf.worker.v1.Worker.StreamLogs:output_type -> wharf.worker.v1.LogStream
	5, // 7: wharf.worker.v1.Worker.StreamStatusEvents:output_type -> wharf.worker.v1.StatusEvent
	6, // 8: wharf.worker.v1.Worker.StreamArtifactEvents:output_type -> wharf.worker.v1.ArtifactEvent
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_workerapi_v1_worker_proto_init() }
func file_api_workerapi_v1_worker_proto_init() {
	if File_api_workerapi_v1_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_workerapi_v1_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_workerapi_v1_worker_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_workerapi_v1_worker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_workerapi_v1_worker_proto_goTypes,
		DependencyIndexes: file_api_workerapi_v1_worker_proto_depIdxs,
		EnumInfos:         file_api_workerapi_v1_worker_proto_enumTypes,
		MessageInfos:      file_api_workerapi_v1_worker_proto_msgTypes,
	}.Build()
	File_api_workerapi_v1_worker_proto = out.File
	file_api_workerapi_v1_worker_proto_rawDesc = nil
	file_api_workerapi_v1_worker_proto_goTypes = nil
	file_api_workerapi_v1_worker_proto_depIdxs = nil
}
