// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pkg/worker/v1/rpc/worker.proto

// Versioning via package name, for future-proofing

package v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusEventsResponse_Status int32

const (
	StatusEventsResponse_SCHEDULING StatusEventsResponse_Status = 0
	StatusEventsResponse_RUNNING    StatusEventsResponse_Status = 1
	StatusEventsResponse_FAILED     StatusEventsResponse_Status = 2
	StatusEventsResponse_COMPLETED  StatusEventsResponse_Status = 3
)

// Enum value maps for StatusEventsResponse_Status.
var (
	StatusEventsResponse_Status_name = map[int32]string{
		0: "SCHEDULING",
		1: "RUNNING",
		2: "FAILED",
		3: "COMPLETED",
	}
	StatusEventsResponse_Status_value = map[string]int32{
		"SCHEDULING": 0,
		"RUNNING":    1,
		"FAILED":     2,
		"COMPLETED":  3,
	}
)

func (x StatusEventsResponse_Status) Enum() *StatusEventsResponse_Status {
	p := new(StatusEventsResponse_Status)
	*p = x
	return p
}

func (x StatusEventsResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusEventsResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_worker_v1_rpc_worker_proto_enumTypes[0].Descriptor()
}

func (StatusEventsResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_worker_v1_rpc_worker_proto_enumTypes[0]
}

func (x StatusEventsResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusEventsResponse_Status.Descriptor instead.
func (StatusEventsResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{4, 0}
}

// Empty messages, but exists for potential future usages
type LogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{0}
}

type StatusEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusEventsRequest) Reset() {
	*x = StatusEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEventsRequest) ProtoMessage() {}

func (x *StatusEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEventsRequest.ProtoReflect.Descriptor instead.
func (*StatusEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{1}
}

type ArtifactEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArtifactEventsRequest) Reset() {
	*x = ArtifactEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactEventsRequest) ProtoMessage() {}

func (x *ArtifactEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactEventsRequest.ProtoReflect.Descriptor instead.
func (*ArtifactEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{2}
}

type LogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogId     int64                `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`    // not DB value; worker's own ID of the log line
	StepId    int32                `protobuf:"varint,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"` // not DB value; worker's own ID of the step ID
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line      string               `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{3}
}

func (x *LogsResponse) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *LogsResponse) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *LogsResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type StatusEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId int32                       `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // not DB value; worker's own ID of the event
	StepId  int32                       `protobuf:"varint,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`    // not DB value; worker's own ID of the step ID
	Status  StatusEventsResponse_Status `protobuf:"varint,3,opt,name=status,proto3,enum=wharf.worker.v1.StatusEventsResponse_Status" json:"status,omitempty"`
}

func (x *StatusEventsResponse) Reset() {
	*x = StatusEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEventsResponse) ProtoMessage() {}

func (x *StatusEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEventsResponse.ProtoReflect.Descriptor instead.
func (*StatusEventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StatusEventsResponse) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *StatusEventsResponse) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *StatusEventsResponse) GetStatus() StatusEventsResponse_Status {
	if x != nil {
		return x.Status
	}
	return StatusEventsResponse_SCHEDULING
}

type ArtifactEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtifactId int32  `protobuf:"varint,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"` // not DB value; worker's own ID of the artifact
	StepId     int32  `protobuf:"varint,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`             // not DB value; worker's own ID of the step ID
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ArtifactEventResponse) Reset() {
	*x = ArtifactEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactEventResponse) ProtoMessage() {}

func (x *ArtifactEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_worker_v1_rpc_worker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactEventResponse.ProtoReflect.Descriptor instead.
func (*ArtifactEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactEventResponse) GetArtifactId() int32 {
	if x != nil {
		return x.ArtifactId
	}
	return 0
}

func (x *ArtifactEventResponse) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *ArtifactEventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pkg_worker_v1_rpc_worker_proto protoreflect.FileDescriptor

var file_pkg_worker_v1_rpc_worker_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70,
	0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65,
	0x22, 0xd2, 0x01, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64, 0x12, 0x44, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e,
	0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x40, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a,
	0x0a, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x03, 0x22, 0x65, 0x0a, 0x15, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x92, 0x02, 0x0a,
	0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x73, 0x12,
	0x1c, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x5d,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x24,
	0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x62, 0x0a,
	0x0e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x26, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x76, 0x65, 0x72, 0x2d, 0x77, 0x68, 0x61, 0x72, 0x66, 0x2f, 0x77, 0x68, 0x61, 0x72, 0x66,
	0x2d, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_worker_v1_rpc_worker_proto_rawDescOnce sync.Once
	file_pkg_worker_v1_rpc_worker_proto_rawDescData = file_pkg_worker_v1_rpc_worker_proto_rawDesc
)

func file_pkg_worker_v1_rpc_worker_proto_rawDescGZIP() []byte {
	file_pkg_worker_v1_rpc_worker_proto_rawDescOnce.Do(func() {
		file_pkg_worker_v1_rpc_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_worker_v1_rpc_worker_proto_rawDescData)
	})
	return file_pkg_worker_v1_rpc_worker_proto_rawDescData
}

var file_pkg_worker_v1_rpc_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_worker_v1_rpc_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_worker_v1_rpc_worker_proto_goTypes = []interface{}{
	(StatusEventsResponse_Status)(0), // 0: wharf.worker.v1.StatusEventsResponse.Status
	(*LogsRequest)(nil),              // 1: wharf.worker.v1.LogsRequest
	(*StatusEventsRequest)(nil),      // 2: wharf.worker.v1.StatusEventsRequest
	(*ArtifactEventsRequest)(nil),    // 3: wharf.worker.v1.ArtifactEventsRequest
	(*LogsResponse)(nil),             // 4: wharf.worker.v1.LogsResponse
	(*StatusEventsResponse)(nil),     // 5: wharf.worker.v1.StatusEventsResponse
	(*ArtifactEventResponse)(nil),    // 6: wharf.worker.v1.ArtifactEventResponse
	(*timestamp.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_pkg_worker_v1_rpc_worker_proto_depIdxs = []int32{
	7, // 0: wharf.worker.v1.LogsResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: wharf.worker.v1.StatusEventsResponse.status:type_name -> wharf.worker.v1.StatusEventsResponse.Status
	1, // 2: wharf.worker.v1.Worker.Logs:input_type -> wharf.worker.v1.LogsRequest
	2, // 3: wharf.worker.v1.Worker.StatusEvents:input_type -> wharf.worker.v1.StatusEventsRequest
	3, // 4: wharf.worker.v1.Worker.ArtifactEvents:input_type -> wharf.worker.v1.ArtifactEventsRequest
	4, // 5: wharf.worker.v1.Worker.Logs:output_type -> wharf.worker.v1.LogsResponse
	5, // 6: wharf.worker.v1.Worker.StatusEvents:output_type -> wharf.worker.v1.StatusEventsResponse
	6, // 7: wharf.worker.v1.Worker.ArtifactEvents:output_type -> wharf.worker.v1.ArtifactEventResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_worker_v1_rpc_worker_proto_init() }
func file_pkg_worker_v1_rpc_worker_proto_init() {
	if File_pkg_worker_v1_rpc_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_worker_v1_rpc_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_worker_v1_rpc_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_worker_v1_rpc_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_worker_v1_rpc_worker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_worker_v1_rpc_worker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_worker_v1_rpc_worker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_worker_v1_rpc_worker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_worker_v1_rpc_worker_proto_goTypes,
		DependencyIndexes: file_pkg_worker_v1_rpc_worker_proto_depIdxs,
		EnumInfos:         file_pkg_worker_v1_rpc_worker_proto_enumTypes,
		MessageInfos:      file_pkg_worker_v1_rpc_worker_proto_msgTypes,
	}.Build()
	File_pkg_worker_v1_rpc_worker_proto = out.File
	file_pkg_worker_v1_rpc_worker_proto_rawDesc = nil
	file_pkg_worker_v1_rpc_worker_proto_goTypes = nil
	file_pkg_worker_v1_rpc_worker_proto_depIdxs = nil
}
